spring:
  application:
    name: appointment-service
  config:
    import: "configserver:http://localhost:8888"
  aop:
    proxy-target-class: true

resilience4j:
  circuitbreaker:
    instances:
      doctorServiceCB:
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
  retry:
    instances:
      patientRetry:
        max-attempts: 3
        wait-duration: 2s


